version: 2
shared: &shared
  environment:
    XDEBUG_MODE: coverage
  steps:
    - checkout
    - run: composer install --prefer-dist
    - run: composer test
    - run: composer validate
jobs:
  "php70":
    docker:
      - image: circleci/php:7.0-cli
    <<: *shared
  "php71":
    docker:
      - image: circleci/php:7.1-cli
    <<: *shared
  "php72":
    docker:
      - image: circleci/php:7.2-cli
    <<: *shared
  "php73":
    docker:
      - image: circleci/php:7.3-cli
    <<: *shared
  "php74":
    docker:
      - image: circleci/php:7.4-cli
    <<: *shared
  "php80":
    docker:
      - image: circleci/php:7.4-cli
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "php70"
      - "php71"
      - "php72"
      - "php73"
      - "php74"
      - "php80"
